FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy only package.json and package-lock.json first
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy full source code
COPY . .

# Build inside container
RUN npm run build

# Install a tiny static server
RUN npm install -g serve

# Default command to serve the built files
CMD ["serve", "-s", "dist", "-l", "8080"]
